### ISSUE TITLE
Error: __init__() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by jpyamamoto** [jofpin/sack#2]
I tried to run the following command:

`go facebook 90`

But it returned the following output:

```
+--=[-> Facebook Pishing
+--=[-> Version: 1.0
+--=[-> Author: Jose Pino, @jofpin
+--=[-> Copyright: 2016

[*] Updating files...
Error: __init__() got an unexpected keyword argument 'strict'
```

I think this is caused by the bs4 module. I could track the following to /libs/bs4/__init.py__:

`STRICT = 'strict'`

**Comment by jofpin** [comment]
Hi, have you tried it with a port of 4 numbers?

**Comment by jpyamamoto** [comment]
Yes, same output

**Comment by RedToor** [comment]
https://github.com/jofpin/sack/blob/master/core/server.py#L33 change to

> from bs4 import BeautifulSoup as bs

**Comment by jpyamamoto** [comment]
Ok, now the following error is appearing:

`Error: 'ascii' codec can't encode character u'\xf3' in position 1227: ordinal not in range(128)`

**Comment by RedToor** [comment]
Comment the line https://github.com/jofpin/sack/blob/master/core/server.py#L328
uncomment the line https://github.com/jofpin/sack/blob/master/core/server.py#L329

**Comment by jpyamamoto** [comment]
Working perfectly, thanks.
